export const SELECT_COLOR: { [key: string]: any } = {
  blue: '#D1DFFC',
  cyan: '#D5EFFB',
  teal: '#CCF3E9',
  green: '#D8F5C8',
  yellow: '#FCEABC',
  orange: '#FAE3D7',
  red: '#F9DDE5',
  pink: '#F9DCF4',
  purple: '#EBE3FC',
  gray: '#EEEEEE',
};

export const CORE_COLORS: { [key: string]: string } = {
  blue: '#3f66f2',
  red: '#f5564e',
  gray: '#7f7972',
  magenta: '#F33F71',
  yellow: '#fabb59',
  orange: '#ff6e2a',
  green: '#25993d',
  black: '#393955',
  pink: '#f355a8',
  purple: '#774df6',
  lightBlue: '#EBEFFD',
  lightRed: '#FBCFCD',
  lightGray: '#D8D6D4',
  lightMagenta: '#FFDEE7',
  lightYellow: '#FFEDD0',
  lightOrange: '#FAD4C2',
  lightGreen: '#DFECE1',
  lightBlack: '#D8D6D4',
  lightPink: '#F9E1EE',
  lightPurple: '#E5E2F1',
};
