export const DATE_FORMAT = {
  LOCAL: 'LOCAL',
  FRIENDLY: 'FRIENDLY',
  EURO: 'EURO',
  ISO: 'ISO',
};

export enum DateFormat {
  LOCAL,
  FRIENDLY,
  EURO,
  ISO,
}

// Need to deprecate this.
export const TIME_FORMAT = {
  TWELVE_HOUR: 'TWELVE_HOUR',
  TWOFOUR_HOUR: 'TWOFOUR_HOUR',
};

export enum TimeFormat {
  TWELVE_HOUR,
  TWOFOUR_HOUR,
}

export const FIELD_TYPES: { [key: string]: any } = {
  TEXT: {
    type: 'TEXT',
    name: 'form.field.name.singleLineText',
    typeOptions: {},
    description: 'form.field.description.text',
    icon: 'FIELD_TEXT',
    valueKey: 'text',
  },
  // MULTILINE_TEXT: {
  //   type: 'MULTILINE_TEXT',
  //   name: 'form.field.name.longText',
  //   typeOptions: {},
  //   description: 'form.field.description.longText',
  //   icon: 'FIELD_LONGTEXT',
  // },
  NUMBER: {
    type: 'NUMBER',
    name: 'form.field.name.number',
    typeOptions: { precision: 1, defaultNumber: 0 },
    description: '',
    icon: 'FIELD_NUMBER',
    valueKey: 'number',
    formatOptions: [
      { nameId: 'form.field.option.decimal', value: 'decimal' },
      { nameId: 'form.field.option.integer', value: 'integer' },
    ],
    precisionOptions: [
      { name: '1.0', value: 1 },
      { name: '1.00', value: 2 },
      { name: '1.000', value: 3 },
      { name: '1.0000', value: 4 },
      { name: '1.00000', value: 5 },
      { name: '1.000000', value: 6 },
      { name: '1.0000000', value: 7 },
      { name: '1.00000000', value: 8 },
    ],
  },
  DATETIME: {
    type: 'DATETIME',
    name: 'form.field.name.date',
    description: 'form.field.description.date',
    icon: 'FIELD_DATE',
    typeOptions: {
      dateFormat: DATE_FORMAT.LOCAL,
      includeTime: false,
      timeFormat: TIME_FORMAT.TWELVE_HOUR,
      useGMT: false,
    },
    dateFormatOptions: [
      { nameId: 'form.field.option.local', value: DATE_FORMAT.LOCAL },
      { nameId: 'form.field.option.friendly', value: DATE_FORMAT.FRIENDLY },
      { nameId: 'form.field.option.european', value: DATE_FORMAT.EURO },
      { nameId: 'form.field.option.iso', value: DATE_FORMAT.ISO },
    ],
    timeFormatOptions: [
      { nameId: 'form.field.option.12hour', value: TIME_FORMAT.TWELVE_HOUR },
      { nameId: 'form.field.option.24hour', value: TIME_FORMAT.TWOFOUR_HOUR },
    ],
    valueKey: 'dateTime',
  },
  RECORD_REFERENCE: {
    type: 'RECORD_REFERENCE',
    name: 'form.field.name.recordReference',
    typeOptions: {},
    description: '',
    icon: 'FIELD_REFERENCE',
    valueKey: 'foreignRow',
  },
  LOOKUP: {
    type: 'LOOKUP',
    name: 'form.field.name.lookup',
    typeOptions: {},
    description: 'form.field.description.lookup',
    icon: 'FIELD_LOOKUP',
    valueKey: 'lookup',
  },
  MULTI_ATTACHMENT: {
    type: 'MULTI_ATTACHMENT',
    name: 'form.field.name.attachment',
    typeOptions: {},
    description: 'form.field.description.attachment',
    icon: 'FIELD_ATTACHMENT',
    valueKey: 'attachments',
  },
  // CHECKBOX: {
  //   type: 'CHECKBOX',
  //   name: 'form.field.name.checkbox',
  //   typeOptions: {},
  //   description: 'form.field.description.checkbox',
  //   icon: 'FIELD_CHECKBOX',
  // },
  MULTI_SELECT: {
    type: 'MULTI_SELECT',
    name: 'form.field.name.multiSelect',
    typeOptions: { choiceOrder: [], choices: {} },
    description: 'form.field.description.multiSelect',
    icon: 'FIELD_MULTISELECT',
    valueKey: 'selectedItems',
  },
  SELECT: {
    type: 'SELECT',
    name: 'form.field.name.singleSelect',
    typeOptions: { choiceOrder: [], choices: {} },
    description: 'form.field.description.singleSelect',
    icon: 'FIELD_SELECT',
    valueKey: 'selectedItem',
  },
};
// COLLABORATOR: {
//   type: 'COLLABORATOR',
//   name: 'form.field.name.collaborator',
//   typeOptions: { multiCollaborator: true, shouldNotify: true },
//   description: 'form.field.description.collaborator',
//   icon: 'FIELD_COLLABORATOR',
// },
// TABLE_REFERENCE: {
//   type: 'TABLE_REFERENCE',
//   name: 'form.field.name.tableReference',
//   typeOptions: {},
//   description: '',
//   icon: 'FIELD_TABLE_REFERENCE',
// },
// FORMULA: {
//   type: 'FORMULA',
//   name: 'form.field.name.formula',
//   typeOptions: { referencedColumnIdsForValue: [], formulaTextParsed: '' },
//   description: 'form.field.description.formula',
//   icon: 'FIELD_FORMULA',
//   functions: [
//     { name: 'AVERAGE()', type: 'function', value: 'AVERAGE()' },
//     { name: 'COUNT()', type: 'function', value: 'COUNT()' },
//     { name: 'COUNTA()', type: 'function', value: 'COUNTA()' },
//     { name: 'SUM()', type: 'function', value: 'SUM()' },
//     { name: 'MIN()', type: 'function', value: 'MIN()' },
//     { name: 'MAX()', type: 'function', value: 'MAX()' },
//     { name: 'AND()', type: 'function', value: 'AND()' },
//     { name: 'OR()', type: 'function', value: 'OR()' },
//   ],
//   formatOptions: [
//     { name: 'field.modal.fieldOptions.format.decimal', value: 'decimal' },
//     { name: 'field.modal.fieldOptions.format.integer', value: 'integer' },
//     { name: 'field.modal.fieldOptions.format.percent', value: 'percent' },
//     { name: 'field.modal.fieldOptions.format.duration', value: 'duration' },
//   ],
//   decimal: [
//     { name: '1.0', value: 1 },
//     { name: '1.00', value: 2 },
//     { name: '1.000', value: 3 },
//     { name: '1.0000', value: 4 },
//     { name: '1.00000', value: 5 },
//     { name: '1.000000', value: 6 },
//     { name: '1.0000000', value: 7 },
//     { name: '1.00000000', value: 8 },
//   ],
//   percent: [
//     { name: '1%', value: 0 },
//     { name: '1.0%', value: 1 },
//     { name: '1.00%', value: 2 },
//     { name: '1.000%', value: 3 },
//     { name: '1.0000%', value: 4 },
//     { name: '1.00000%', value: 5 },
//     { name: '1.000000%', value: 6 },
//     { name: '1.0000000%', value: 7 },
//     { name: '1.00000000%', value: 8 },
//   ],
//   duration: [
//     { name: 'h:mm(e.g. 1:23)', value: 'h:mm' },
//     { name: 'h:mm:ss(e.g. 3:45, 1.23:40)', value: 'h:mm:ss' },
//     { name: 'h:mm:ss.s(e.g. 3:45.6, 1.23:40.0)', value: 'h:mm:ss.s' },
//     { name: 'h:mm:ss.ss(e.g. 3.45.67, 1.23:40.00)', value: 'h:mm:ss.ss' },
//     { name: 'h:mm:ss.sss(e.g. 3.45.678, 1.23:40.000)', value: 'h:mm:ss.sss' },
//   ],
// },
