import { IAdaptedAttachment } from '@app/renderer/types';
import { CellClickedEvent } from 'ag-grid-community';

import { LAST_COL_PROPS } from '@app/renderer/constants/grid';

export const fakeData3 = {
  data: {
    workspace: [
      {
        uid: '0x1',
        id: 'wspb552a9efe70869a5',
        name: 'Sample Workspace',
        cores: [
          {
            uid: '0x2',
            id: 'creb552ab1e5a854604',
            name: 'test core',
            tables: [
              {
                uid: '0x3',
                id: 'tblb552ab1e750611a7',
                name: 'Table 1',
                views: [
                  {
                    uid: '0x9',
                    id: 'viwb552ab1e7a047436',
                    name: 'Grid View',
                    columns: [
                      {
                        uid: '0x4',
                        id: 'colb552ab1e7983bb97',
                        name: 'Name',
                        columnType: 'TEXT',
                        'columns|order': 0,
                      },
                      {
                        uid: '0x5',
                        id: 'colb552ab1e79895e84',
                        name: 'Notes',
                        columnType: 'TEXT',
                        'columns|order': 1,
                      },
                      {
                        uid: '0x13',
                        id: 'colb552aff11b0316c4',
                        name: 'Table 1',
                        columnType: 'FOREIGN_KEY',
                        cells: [
                          {
                            uid: '0x15',
                            columnId: 'colb552aff11b0316c4',
                            rowId: 'rowb552ab1e7a043104',
                            cellType: 'FOREIGN_KEY',
                            foreignRow: [
                              {
                                uid: '0x10',
                                id: 'rowb552aeff2e8c07ce',
                              },
                            ],
                          },
                        ],
                        'columns|order': 2,
                      },
                    ],
                    rows: [
                      {
                        uid: '0x6',
                        id: 'row001',
                        'rows|order': 0,
                      },
                      {
                        uid: '0x7',
                        id: 'row002',
                        'rows|order': 1,
                      },
                      {
                        uid: '0x8',
                        id: 'row003',
                        cells: [
                          {
                            uid: '0xa',
                            columnId: 'colb552ab1e7983bb97',
                            rowId: 'rowb552ab1e7a043104',
                            cellType: 'TEXT',
                            text: 'Simon',
                          },
                          {
                            uid: '0x15',
                            columnId: 'colb552aff11b0316c4',
                            rowId: 'rowb552ab1e7a043104',
                            cellType: 'FOREIGN_KEY',
                            foreignRow: [
                              {
                                uid: '0x10',
                                id: 'rowb552aeff2e8c07ce',
                              },
                            ],
                          },
                        ],
                        'rows|order': 2,
                      },
                      {
                        uid: '0x8',
                        id: 'row004',
                        cells: [
                          {
                            uid: '0xa',
                            columnId: 'colb552ab1e7983bb97',
                            rowId: 'rowb552ab1e7a043104',
                            cellType: 'TEXT',
                            text: 'Simon',
                          },
                          {
                            uid: '0x15',
                            columnId: 'colb552aff11b0316c4',
                            rowId: 'rowb552ab1e7a043104',
                            cellType: 'FOREIGN_KEY',
                            foreignRow: [
                              {
                                uid: '0x10',
                                id: 'rowb552aeff2e8c07ce',
                              },
                            ],
                          },
                        ],
                      },
                      {
                        uid: '0x8',
                        id: 'row005',
                        cells: [
                          {
                            uid: '0xa',
                            columnId: 'colb552ab1e7983bb97',
                            rowId: 'rowb552ab1e7a043104',
                            cellType: 'TEXT',
                            text: 'Simon',
                          },
                          {
                            uid: '0x15',
                            columnId: 'colb552aff11b0316c4',
                            rowId: 'rowb552ab1e7a043104',
                            cellType: 'FOREIGN_KEY',
                            foreignRow: [
                              {
                                uid: '0x10',
                                id: 'rowb552aeff2e8c07ce',
                              },
                            ],
                          },
                        ],
                      },
                      {
                        uid: '0x8',
                        id: 'row006',
                        cells: [
                          {
                            uid: '0xa',
                            columnId: 'colb552ab1e7983bb97',
                            rowId: 'rowb552ab1e7a043104',
                            cellType: 'TEXT',
                            text: 'Simon',
                          },
                          {
                            uid: '0x15',
                            columnId: 'colb552aff11b0316c4',
                            rowId: 'rowb552ab1e7a043104',
                            cellType: 'FOREIGN_KEY',
                            foreignRow: [
                              {
                                uid: '0x10',
                                id: 'rowb552aeff2e8c07ce',
                              },
                            ],
                          },
                        ],
                      },
                      {
                        uid: '0x8',
                        id: 'row007',
                        cells: [
                          {
                            uid: '0xa',
                            columnId: 'colb552ab1e7983bb97',
                            rowId: 'rowb552ab1e7a043104',
                            cellType: 'TEXT',
                            text: 'Simon',
                          },
                          {
                            uid: '0x15',
                            columnId: 'colb552aff11b0316c4',
                            rowId: 'rowb552ab1e7a043104',
                            cellType: 'FOREIGN_KEY',
                            foreignRow: [
                              {
                                uid: '0x10',
                                id: 'rowb552aeff2e8c07ce',
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
};

export const attachments: IAdaptedAttachment[] = [
  {
    url: 'https://cdn.filestackcontent.com/yf3Geor9QrWqOluDvU0X',
    fileName: 'xunguang-4.jpg',
    fileType: 'image/jpeg',
    smallThumbUrl:
      'https://cdn.filestackcontent.com/output=format:png,density:15,compress:true/resize=height:36/yf3Geor9QrWqOluDvU0X',
    largeThumbUrl:
      'https://cdn.filestackcontent.com/output=format:png,density:15,compress:true/resize=height:350/yf3Geor9QrWqOluDvU0X',
    fullThumbUrl:
      'https://cdn.filestackcontent.com/output=format:png,density:15,compress:true/resize=height:350/yf3Geor9QrWqOluDvU0X',
    fileId: 'yf3Geor9QrWqOluDvU0X',
  },
  {
    url: 'https://cdn.filestackcontent.com/NJ4IXOSXSoOb5kgcJDuq',
    fileName: 'document.pdf',
    fileType: 'application/pdf',
    smallThumbUrl:
      'https://cdn.filestackcontent.com/output=format:png,density:15,compress:true/resize=height:36/NJ4IXOSXSoOb5kgcJDuq',
    largeThumbUrl:
      'https://cdn.filestackcontent.com/output=format:png,density:15,compress:true/resize=height:350/NJ4IXOSXSoOb5kgcJDuq',
    fullThumbUrl:
      'https://cdn.filestackcontent.com/output=format:png,density:15,compress:true/resize=height:350/NJ4IXOSXSoOb5kgcJDuq',
    fileId: 'NJ4IXOSXSoOb5kgcJDuq',
  },
  {
    url: 'https://cdn.filestackcontent.com/qNklAKuMSmq5tdHUPjVN',
    fileName: 'chick.png',
    fileType: 'image/png',
    smallThumbUrl:
      'https://cdn.filestackcontent.com/output=format:png,density:15,compress:true/resize=height:36/qNklAKuMSmq5tdHUPjVN',
    largeThumbUrl:
      'https://cdn.filestackcontent.com/output=format:png,density:15,compress:true/resize=height:350/qNklAKuMSmq5tdHUPjVN',
    fullThumbUrl:
      'https://cdn.filestackcontent.com/output=format:png,density:15,compress:true/resize=height:350/qNklAKuMSmq5tdHUPjVN',
    fileId: 'qNklAKuMSmq5tdHUPjVN',
  },
];

const selectedForeignRows: any[] = [
  {
    foreignRowId: 'row1',
    foreignRowName: 'hahah',
  },
  {
    foreignRowId: 'row2',
    foreignRowName: 'Grid',
  },
];

export const coreViewData = {
  workspace: {
    id: 'wspb5170142c18cd8a2',
    name: 'Osman',
    cores: [
      {
        color: 'gray',
        icon: 'barChart',
        id: 'creb546125ee30dfeff',
        name: 'Orders',
        tables: [
          {
            id: 'tblb546125f148a4df5',
            name: 'Table 1',
            tableData: {
              rows: [
                { id: 'rowb546125f3882796d', cells: [], __typename: 'RowData' },
                { id: 'rowb546125f38868244', cells: [], __typename: 'RowData' },
                { id: 'rowb546125f388706ce', cells: [], __typename: 'RowData' },
              ],
            },
            viewDatas: [
              {
                id: 'viwb546125f3887a927',
                name: 'Grid View',
                type: 'GRID',
                columns: [
                  {
                    id: 'colb546125f378d7923',
                    name: 'Name',
                    type: 'TEXT',
                    order: 0,
                    visibility: true,
                  },
                  {
                    id: 'colb546125f3807a290',
                    name: 'Notes',
                    type: 'TEXT',
                    order: 1,
                    visibility: true,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
};

export const columnDefs = [
  {
    headerName: 'Athlete',
    field: 'athlete',
    width: 200,
    pinned: 'left',
    cellRenderer: 'gridCellTextRenderer',
    cellEditor: 'gridCellTextEditor',
    headerComponent: 'headerCell',
    filter: 'agTextColumnFilter',
  },
  {
    headerName: 'Age',
    field: 'age',
    width: 200,
    cellRenderer: 'gridCellNumberRenderer',
    cellEditor: 'gridCellNumberEditor',
    headerComponent: 'headerCell',
    filter: 'agNumberColumnFilter',
  },
  {
    headerName: 'Country',
    field: 'country',
    width: 200,
    headerComponent: 'headerCell',
    cellRenderer: 'gridCellSelectRenderer',
    cellEditor: 'gridCellSelectEditor',
  },
  {
    headerName: 'Description',
    field: 'description',
    width: 200,
    cellRenderer: 'gridCellMultilineTextRenderer',
    cellEditor: 'gridCellMultilineTextEditor',
    headerComponent: 'headerCell',
    filter: 'agTextColumnFilter',
  },
  {
    headerName: 'Reference',
    field: 'reference',
    width: 200,
    cellRenderer: 'gridCellReferenceRenderer',
    cellEditor: 'gridCellReferenceEditor',
    headerComponent: 'headerCell',
  },
  {
    headerName: 'Year',
    field: 'year',
    width: 200,
    cellRenderer: 'gridCellNumberRenderer',
    cellEditor: 'gridCellNumberEditor',
    headerComponent: 'headerCell',
    filter: 'agNumberColumnFilter',
  },
  {
    headerName: 'Date',
    field: 'date',
    width: 200,
    cellRenderer: 'gridCellDateRenderer',
    cellEditor: 'gridCellDateEditor',
    headerComponent: 'headerCell',
    filter: 'agNumberColumnFilter',
  },
  {
    headerName: 'Sport',
    field: 'sport',
    width: 200,
    cellRenderer: 'gridCellMultiSelectRenderer',
    cellEditor: 'gridCellMultiSelectEditor',
    headerComponent: 'headerCell',
    filter: 'agTextColumnFilter',
  },
  {
    headerName: 'Gold',
    field: 'gold',
    width: 200,
    cellRenderer: 'gridCellNumberRenderer',
    cellEditor: 'gridCellNumberEditor',
    headerComponent: 'headerCell',
    filter: 'agNumberColumnFilter',
  },
  {
    headerName: 'Silver',
    field: 'silver',
    width: 200,
    cellRenderer: 'gridCellNumberRenderer',
    cellEditor: 'gridCellNumberEditor',
    headerComponent: 'headerCell',
    filter: 'agNumberColumnFilter',
  },
  {
    headerName: 'Bronze',
    field: 'bronze',
    width: 200,
    cellRenderer: 'gridCellNumberRenderer',
    cellEditor: 'gridCellNumberEditor',
    headerComponent: 'headerCell',
    filter: 'agNumberColumnFilter',
  },
  {
    headerName: 'Total',
    field: 'total',
    width: 200,
    cellRenderer: 'gridCellNumberRenderer',
    cellEditor: 'gridCellNumberEditor',
    headerComponent: 'headerCell',
    filter: 'agNumberColumnFilter',
    // TODO @Derek figure out a way to inject this better
    ...LAST_COL_PROPS,
  },
  {
    headerName: 'Retired',
    field: 'retired',
    width: 200,
    cellRenderer: 'gridCellCheckboxRenderer',
    cellEditor: 'gridCellCheckboxEditor',
    headerComponent: 'headerCell',
  },
  {
    headerName: 'Picture',
    field: 'picture',
    width: 200,
    cellRenderer: 'gridCellAttachmentRenderer',
    cellEditor: 'gridCellAttachmentEditor',
    headerComponent: 'headerCell',
    filter: 'agNumberColumnFilter',
  },
];

export const rowData = [
  {
    athlete: 'Michael Phelps',
    age: 23,
    country: 'cs1',
    picture: attachments,
    description: 'Great!',
    reference: selectedForeignRows,
    year: 2008,
    date: '2008-08-24',
    sport: ['cs1'],
    gold: 8,
    silver: 0,
    bronze: 0,
    total: 8,
    retired: true,
  },
  {
    athlete: 'Michael Phelps',
    age: 19,
    country: 'cs1',
    picture: attachments,
    description: 'Great!',
    reference: selectedForeignRows,
    year: 2004,
    date: '2004-08-24',
    sport: ['cs1'],
    gold: 6,
    silver: 0,
    bronze: 2,
    total: 8,
    retired: true,
  },
  {
    athlete: 'Michael Phelps',
    age: 27,
    country: 'cs1',
    picture: attachments,
    description: 'Great!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 4,
    silver: 2,
    bronze: 0,
    total: 6,
    retired: true,
  },
  {
    athlete: 'Natalie Coughlin',
    age: 25,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2008,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 1,
    silver: 2,
    bronze: 3,
    total: 6,
  },
  {
    athlete: 'Aleksey Nemov',
    age: 24,
    country: 'cs2',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2000,
    date: '2008-12-24',
    sport: ['cs2'],
    gold: 2,
    silver: 1,
    bronze: 3,
    total: 6,
  },
  {
    athlete: 'Alicia Coutts',
    age: 24,
    country: 'cs3',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 1,
    silver: 3,
    bronze: 1,
    total: 5,
  },
  {
    athlete: 'Missy Franklin',
    age: 17,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs2'],
    gold: 4,
    silver: 0,
    bronze: 1,
    total: 5,
  },
  {
    athlete: 'Michael Phelps',
    age: 23,
    country: 'cs1',
    picture: attachments,
    description: 'Great!',
    reference: selectedForeignRows,
    year: 2008,
    date: '2008-12-24',
    sport: ['cs3'],
    gold: 8,
    silver: 0,
    bronze: 0,
    total: 8,
  },
  {
    athlete: 'Michael Phelps',
    age: 19,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2004,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 6,
    silver: 0,
    bronze: 2,
    total: 8,
  },
  {
    athlete: 'Michael Phelps',
    age: 27,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 4,
    silver: 2,
    bronze: 0,
    total: 6,
  },
  {
    athlete: 'Natalie Coughlin',
    age: 25,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2008,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 1,
    silver: 2,
    bronze: 3,
    total: 6,
  },
  {
    athlete: 'Aleksey Nemov',
    age: 24,
    country: 'cs2',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2000,
    date: '2008-12-24',
    sport: ['cs4'],
    gold: 2,
    silver: 1,
    bronze: 3,
    total: 6,
  },
  {
    athlete: 'Alicia Coutts',
    age: 24,
    country: 'cs3',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 1,
    silver: 3,
    bronze: 1,
    total: 5,
  },
  {
    athlete: 'Missy Franklin',
    age: 17,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 4,
    silver: 0,
    bronze: 1,
    total: 5,
  },
  {
    athlete: 'Ryan Lochte',
    age: 27,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 2,
    bronze: 1,
    total: 5,
  },
  {
    athlete: 'Allison Schmitt',
    age: 22,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 3,
    silver: 1,
    bronze: 1,
    total: 5,
  },
  {
    athlete: 'Natalie Coughlin',
    age: 21,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2004,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 2,
    bronze: 1,
    total: 5,
  },
  {
    athlete: 'Ian Thorpe',
    age: 17,
    country: 'cs3',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2000,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 3,
    silver: 2,
    bronze: 0,
    total: 5,
  },
  {
    athlete: 'Dara Torres',
    age: 33,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2000,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 0,
    bronze: 3,
    total: 5,
  },
  {
    athlete: 'Cindy Klassen',
    age: 26,
    country: 'cs4',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2006,
    date: '2008-12-24',
    sport: ['cs4'],
    gold: 1,
    silver: 2,
    bronze: 2,
    total: 5,
  },
  {
    athlete: 'Nastia Liukin',
    age: 18,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2008,
    date: '2008-12-24',
    sport: ['cs4'],
    gold: 1,
    silver: 3,
    bronze: 1,
    total: 5,
  },
  {
    athlete: 'Marit Bjørgen',
    age: 29,
    country: 'cs5',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2010,
    date: '2008-12-24',
    sport: ['cs4'],
    gold: 3,
    silver: 1,
    bronze: 1,
    total: 5,
  },
  {
    athlete: 'Sun Yang',
    age: 20,
    country: 'cs6',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
  },
  {
    athlete: 'Libby Lenton-Trickett',
    age: 23,
    country: 'cs3',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2008,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
  },
  {
    athlete: 'Ryan Lochte',
    age: 24,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2008,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 0,
    bronze: 2,
    total: 4,
  },
  {
    athlete: 'Inge de Bruijn',
    age: 30,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2004,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 1,
    silver: 1,
    bronze: 2,
    total: 4,
  },
  {
    athlete: 'Petria Thomas',
    age: 28,
    country: 'cs3',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2004,
    date: '29/08/2004',
    sport: ['cs1'],
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 4,
  },
  {
    athlete: 'Ian Thorpe',
    age: 21,
    country: 'cs3',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2004,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
  },
  {
    athlete: 'Inge de Bruijn',
    age: 27,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2000,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 4,
  },
  {
    athlete: 'Gary Hall Jr.',
    age: 25,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2000,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
  },
  {
    athlete: 'Michael Klim',
    age: 23,
    country: 'cs3',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2000,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 2,
    bronze: 0,
    total: 4,
  },
  {
    athlete: "Susie O'Neill",
    age: 27,
    country: 'cs3',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2000,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 1,
    silver: 3,
    bronze: 0,
    total: 4,
  },
  {
    athlete: 'Jenny Thompson',
    age: 27,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2000,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 3,
    silver: 0,
    bronze: 1,
    total: 4,
  },
  {
    athlete: 'Pieter van den Hoogenband',
    age: 22,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2000,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 0,
    bronze: 2,
    total: 4,
  },
  {
    athlete: 'An Hyeon-Su',
    age: 20,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2006,
    date: '2008-12-24',
    sport: ['cs4'],
    gold: 3,
    silver: 0,
    bronze: 1,
    total: 4,
  },
  {
    athlete: 'Aliya Mustafina',
    age: 17,
    country: 'cs2',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs4'],
    gold: 1,
    silver: 1,
    bronze: 2,
    total: 4,
  },
  {
    athlete: 'Shawn Johnson',
    age: 16,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2008,
    date: '2008-12-24',
    sport: ['cs2'],
    gold: 1,
    silver: 3,
    bronze: 0,
    total: 4,
  },
  {
    athlete: 'Dmitry Sautin',
    age: 26,
    country: 'cs2',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2000,
    date: '2008-12-24',
    sport: ['cs3'],
    gold: 1,
    silver: 1,
    bronze: 2,
    total: 4,
  },
  {
    athlete: 'Leontien Zijlaard-van Moorsel',
    age: 30,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2000,
    date: '2008-12-24',
    sport: ['cs5'],
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 4,
  },
  {
    athlete: 'Petter Northug Jr.',
    age: 24,
    country: 'cs5',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2010,
    date: '2008-12-24',
    sport: ['cs6'],
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
  },
  {
    athlete: 'Ole Einar Bjørndalen',
    age: 28,
    country: 'cs5',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2002,
    date: '2008-12-24',
    sport: ['cs4'],
    gold: 4,
    silver: 0,
    bronze: 0,
    total: 4,
  },
  {
    athlete: 'Janica Kostelic',
    age: 20,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2002,
    date: '2008-12-24',
    sport: ['cs4'],
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 4,
  },
  {
    athlete: 'Nathan Adrian',
    age: 23,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
  },
  {
    athlete: 'Yannick Agnel',
    age: 20,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
  },
  {
    athlete: 'Brittany Elmslie',
    age: 18,
    country: 'cs3',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
  },
  {
    athlete: 'Matt Grevers',
    age: 27,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
  },
  {
    athlete: 'Ryosuke Irie',
    age: 22,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 3,
  },
  {
    athlete: 'Cullen Jones',
    age: 28,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
  },
  {
    athlete: 'Ranomi Kromowidjojo',
    age: 21,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
  },
  {
    athlete: 'Camille Muffat',
    age: 22,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
  },
  {
    athlete: 'Mel Schlanger',
    age: 25,
    country: 'cs3',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
  },
  {
    athlete: 'Emily Seebohm',
    age: 20,
    country: 'cs3',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
  },
  {
    athlete: 'Rebecca Soni',
    age: 25,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
  },
  {
    athlete: 'Satomi Suzuki',
    age: 21,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 3,
  },
  {
    athlete: 'Dana Vollmer',
    age: 24,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2012,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
  },
  {
    athlete: 'Alain Bernard',
    age: 25,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2008,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
  },
  {
    athlete: 'László Cseh Jr.',
    age: 22,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    reference: selectedForeignRows,
    year: 2008,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 0,
    silver: 3,
    bronze: 0,
    total: 3,
  },
  {
    athlete: 'Matt Grevers',
    age: 23,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    year: 2008,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
  },
  {
    athlete: 'Margaret Hoelzer',
    age: 25,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    year: 2008,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 3,
  },
  {
    athlete: 'Katie Hoff',
    age: 19,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    year: 2008,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 3,
  },
  {
    athlete: 'Leisel Jones',
    age: 22,
    country: 'cs3',
    picture: attachments,
    description: 'Good!',
    year: 2008,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
  },
  {
    athlete: 'Kosuke Kitajima',
    age: 25,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    year: 2008,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 3,
  },
  {
    athlete: 'Andrew Lauterstein',
    age: 21,
    country: 'cs3',
    picture: attachments,
    description: 'Good!',
    year: 2008,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 3,
  },
  {
    athlete: 'Jason Lezak',
    age: 32,
    country: 'cs1',
    picture: attachments,
    description: 'Good!',
    year: 2008,
    date: '2008-12-24',
    sport: ['cs1'],
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 3,
  },
];
